### ISSUE TITLE
MQTT Interface topic not updating to "Offline' state

### ISSUE THREAD

**Issue by cdk222** [jpbarraca/pai#55]
**System**
Paradox MG5050 v4.133
IP150 firmware 1.39
Using Dev branch

**Describe the bug**
The state/value in the 'paradox/interface/MQTTInterface' topic does not change to 'offline' when you disconnect/stop the pai script. I also tested this by entering in the wrong user/pass MQTT credentials in the pai.conf thus causing the script to not connect MQTT on startup. In each case the state is always "Online". The topic does seem to update the "Online" state though without issue.

**To Reproduce**
Steps to reproduce the behavior (2 methods):
METHOD 1:
1. Start script
2. Control C to disconnect/stop the script
3. View the 'paradox/interface/MQTTInterface' topic value in MQTT client

METHOD 2:
1. Modify MQTT username or password credentials in pai.conf so that they are incorrect
2. Start script
3. View the 'paradox/interface/MQTTInterface' topic value in MQTT client

**Comment by jpbarraca** [comment]
Method 2 should not change the value as it will not connect correctly.

Method 1 should work as we are setting a last will.

What broker are you using?

**Comment by cdk222** [comment]
I am using Mosquitto MQTT on a pi - same pi and the paradox scripts. 

True on Method 2

**Comment by cdk222** [comment]
Hi - thanks for working on this. I have loaded the changes and the issue is still present. Now I have the below error appearing (from my log - in DEBUG mode)

2019-03-14 18:35:12,285 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2019-03-14 18:35:12,454 - ERROR    - PAI.paradox.paradox - Got ERROR Message: Requested command did not work
2019-03-14 18:35:12,456 - DEBUG    - PAI.paradox.interfaces.interface_manager - Stopping all interfaces
2019-03-14 18:35:12,457 - DEBUG    - PAI.paradox.interfaces.interface_manager - 	mqtt
2019-03-14 18:35:12,459 - DEBUG    - PAI.paradox.interfaces.mqtt_interface - Stopping MQTT Interface
2019-03-14 18:35:12,461 - INFO     - PAI.paradox.interfaces.mqtt_interface - MQTT Broker Disconnected
2019-03-14 18:35:13,469 - DEBUG    - PAI.paradox.interfaces.interface_manager - All Interfaces stopped
2019-03-14 18:35:13,470 - INFO     - PAI - Good bye!

**Comment by cdk222** [comment]
The reason I would like to get this working is that I have an availability sensor attached to the topic:

paradox/interface/MQTTInterface

so that it will report when the paradox mqtt connection has disconnected for an unknown reason

**Comment by jpbarraca** [comment]
Your scenario is perfectly valid.
I tried to replicate the issue, but after the patch it seems to work properly, and I cannot replicate it...

```
paradox/interface/MQTTInterface online  # started
paradox/interface/MQTTInterface offline  # Stopped with CTRL-C
paradox/interface/MQTTInterface online  # started
paradox/interface/MQTTInterface offline  # Stopped with Kill
paradox/interface/MQTTInterface online  # Started with systemctl
paradox/interface/MQTTInterface offline  # Stopped with systemctl
```

**Comment by cdk222** [comment]
Any ideas on what causes the following message:

2019-03-14 18:35:12,454 - ERROR - PAI.paradox.paradox - Got ERROR Message: Requested command did not work

It appears just after the disconnection message

**Comment by cdk222** [comment]
Ok so after a lot of trial and error I was able to rectify this as the above fix did not work for me. I relocated the _'offline'_ state change in the **_mqtt_interface.py_** file so that it was called in the _'stop'_ function and not _'handle_disconnect'_. It appeared that the MQTT connection was already disconnected by the time the topic change to offline was called for. I also changed to '_self.mqtt.will_set_' to '_self.publish_'. Below is the change:

`   

    def stop(self):
        """ Stops the MQTT Interface Thread"""
        self.publish('{}/{}/{}'.format(cfg.MQTT_BASE_TOPIC,
                                       cfg.MQTT_INTERFACE_TOPIC,
                                       self.__class__.__name__),
                     'offline', 0, cfg.MQTT_RETAIN)
        self.mqtt.disconnect()
        self.logger.debug("Stopping MQTT Interface")
        self.queue.put_nowait(SortableTuple((0, 'command', 'stop')))
        self.mqtt.loop_stop()
        self.join()

        `

Tested in my client and state now changes correctly

**Comment by cdk222** [comment]
Hi there

Just messaged you on Gitter about the Paradox asyncio code and the error it
gave me when trying to connect to the panel. Attached is my log file.

cheers

Chad

**Comment by yozik04** [comment]
asyncio is work in progress... Do not use it yet.

**Comment by yozik04** [comment]
I think this one is fixed in **dev** branch. Non-retained version is also in **master**.

Reopen if not.

**Comment by yellowonblack** [comment]
Still not working for me https://github.com/jpbarraca/pai/issues/57#issuecomment-479912846

**Comment by yellowonblack** [comment]
Just sent you, both PAI and MQTT logs for **dev** branch commit 60249ec
